name: mirror

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Clone
        run: |
          git clone https://gitee.com/bling_yshs/Yunzai-v3-Installation-Steps tmp
          cp -r tmp/* .
          
      - name: Push
        run: |
          git config user.name "valetzx"
          git config user.email "550029691@qq.com"
          git add .
          git commit -m "GitHub Actions Make Star at time"
          git push --quiet "https://${{ secrets.MY_TOKEN }}@github.com/bling-yshs/github-pull-test" HEAD:main
